# Generated by Django 2.2.6 on 2021-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='租车方式')),
            ],
            options={
                'verbose_name': '租车方式',
                'verbose_name_plural': '租车方式',
            },
        ),
        migrations.CreateModel(
            name='Issue_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='问题状态')),
            ],
            options={
                'verbose_name': '问题状态',
                'verbose_name_plural': '问题状态',
            },
        ),
        migrations.CreateModel(
            name='OtherEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='特殊工作环境')),
            ],
            options={
                'verbose_name': '特殊工作环境',
                'verbose_name_plural': '特殊工作环境',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('worklog', models.SmallIntegerField(blank=True, null=True, verbose_name='日志汇报')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(Project) 项目')),
                ('facility', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(Facility) 项目设备')),
                ('outsourcer', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(Outsourcer) 承包商')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('user', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(user) 汇报人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='来源')),
                ('bagin_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('count', models.SmallIntegerField(verbose_name='任务数量')),
                ('progress', models.SmallIntegerField(default=0, verbose_name='已完成数量')),
                ('title', models.CharField(max_length=64, verbose_name='任务名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务正文')),
                ('submitter', models.SmallIntegerField(verbose_name='关联-(user) 提交人')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(project) 项目信息')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task_Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='来源')),
            ],
            options={
                'verbose_name': '来源',
                'verbose_name_plural': '来源',
            },
        ),
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
            },
        ),
        migrations.CreateModel(
            name='TaskLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='操作信息')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('user_name', models.CharField(max_length=64, verbose_name='操作人名字')),
                ('task', models.SmallIntegerField(verbose_name='关联-(task) 任务单')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('work_status', models.SmallIntegerField(verbose_name='工作状态')),
                ('issue_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='问题状态')),
                ('other_env', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(OtherEnv) 其它环境')),
                ('isDrive', models.BooleanField(blank=True, null=True, verbose_name='是否开车')),
                ('car_rental', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(CarRental) 租车情况')),
                ('cart_fee', models.SmallIntegerField(blank=True, null=True, verbose_name='租车费')),
                ('other_fee', models.SmallIntegerField(blank=True, null=True, verbose_name='其它车费')),
                ('plan', models.TextField(verbose_name='明日计划')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(project) 项目')),
                ('user', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(user) 汇报人')),
                ('ln_worklog', models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(WorkLog) 项目')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='工作状态')),
            ],
            options={
                'verbose_name': '工作状态',
                'verbose_name_plural': '工作状态',
            },
        ),
    ]
