# Generated by Django 2.2.6 on 2021-08-04 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='Task_exe', to=settings.AUTH_USER_MODEL, verbose_name='关联-(user) 执行人'),
        ),
        migrations.AddField(
            model_name='task',
            name='subscriber',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='Task_sub', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
