# Generated by Django 2.2.6 on 2021-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0003_auto_20210804_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='issue_status',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='otherenv',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='specialenv',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='task_priority',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='task_status',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
