# Generated by Django 2.2.6 on 2021-08-16 17:30

from django.db import migrations, models
import utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0005_worklogs_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to=utils.basemodel.upload_path_image, verbose_name='附件')),
                ('task', models.SmallIntegerField(verbose_name='关联-(task) 任务单')),
            ],
        ),
    ]
