# Generated by Django 2.2.6 on 2021-08-19 10:04

from django.db import migrations, models
import utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0007_auto_20210818_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.basemodel.upload_path_file, verbose_name='附件'),
        ),
    ]
