# Generated by Django 2.2.6 on 2021-08-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0008_auto_20210819_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfile',
            old_name='name',
            new_name='title',
        ),
    ]
