# Generated by Django 2.2.6 on 2020-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='user', to='rbac.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader_dept',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='leader', to='personnel.Structure'),
        ),
    ]
