# Generated by Django 2.2.6 on 2020-06-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='parent',
            new_name='parentid',
        ),
    ]
