# Generated by Django 2.2.6 on 2020-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20201022_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leader_dept',
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1603364145011&di=010785ee75fa3669ca415d95ce401ce0&imgtype=0&src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F201902%2F01%2F20190201234537_SEZMN.thumb.400_0.jpeg', verbose_name='头像链接'),
        ),
    ]
