# Generated by Django 2.2.6 on 2020-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20200817_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader_dept',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='leader', to='personnel.Structure'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='user', to='rbac.Role'),
        ),
    ]
