# Generated by Django 2.2.6 on 2020-06-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20200611_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.Structure', to_field='deptid', verbose_name='父类构架'),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_department',
            field=models.IntegerField(default=0, verbose_name='主部门'),
        ),
    ]
