# Generated by Django 2.2.6 on 2020-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20201116_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(db_constraint=False, related_name='users', to='personnel.Structure'),
        ),
    ]
