# Generated by Django 2.2.6 on 2020-10-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20201023_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(verbose_name='是否领导')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Structure', to_field='deptid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(through='personnel.DeptToUser', to='personnel.Structure'),
        ),
    ]
