# Generated by Django 2.2.6 on 2020-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_auto_20200915_1633'),
        ('personnel', '0003_auto_20200902_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builders', to='engineering.Project'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
