# Generated by Django 2.2.6 on 2020-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20201030_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=2866953378,474015488&fm=11&gp=0.jpg', verbose_name='头像链接'),
        ),
    ]
