# Generated by Django 2.2.6 on 2020-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept_leader',
            field=models.ManyToManyField(db_constraint=False, related_name='leader', to='personnel.Structure'),
        ),
    ]
