# Generated by Django 2.2.6 on 2020-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_user_dept_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
