# Generated by Django 2.2.6 on 2020-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20201023_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(related_name='user', through='personnel.DeptToUser', to='personnel.Structure'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(default=1, verbose_name='性别'),
        ),
    ]
