# Generated by Django 2.2.6 on 2020-11-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20201116_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='personnel.Structure', to_field='deptid', verbose_name='父类构架'),
        ),
    ]
