# Generated by Django 2.2.6 on 2020-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20201124_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depttouser',
            old_name='leader',
            new_name='isleader',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(related_name='member', through='personnel.DeptToUser', to='personnel.Structure'),
        ),
    ]
