# Generated by Django 2.2.6 on 2020-12-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_auto_20201204_2133'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='depttouser',
            table='user_departments',
        ),
    ]
