# Generated by Django 2.2.6 on 2020-12-04 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_auto_20201204_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depttouser',
            name='department',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='personnel.Structure', to_field='deptid'),
        ),
        migrations.AlterField(
            model_name='depttouser',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterModelTable(
            name='structure',
            table='department',
        ),
    ]
