# Generated by Django 2.2.6 on 2021-03-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='通道名称')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='通道数量')),
            ],
            options={
                'verbose_name': '通道信息',
                'verbose_name_plural': '通道信息',
            },
        ),
        migrations.CreateModel(
            name='Lifecycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='产品编号')),
            ],
            options={
                'verbose_name': '生命周期',
                'verbose_name_plural': '生命周期',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='采集器名称')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
                ('hard_version', models.CharField(max_length=64, verbose_name='硬件版本')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='采集器照片')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('aisle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Aisle')),
            ],
            options={
                'verbose_name': '公司产品',
                'verbose_name_plural': '公司产品',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='产品编号')),
            ],
            options={
                'verbose_name': '产品使用状态',
                'verbose_name_plural': '产品使用状态',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='产品编号')),
                ('facility', models.CharField(blank=True, max_length=64, null=True, verbose_name='绑定设备')),
                ('sw', models.CharField(blank=True, max_length=32, null=True, verbose_name='嵌入式版本')),
                ('ip', models.TextField(blank=True, null=True, verbose_name='采集器IP')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('lifecycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='product.Lifecycle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='product.Product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='engineering.Project')),
            ],
            options={
                'verbose_name': '生产出的采集器',
                'verbose_name_plural': '生产出的采集器',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.ProductStatus'),
        ),
    ]
