# Generated by Django 2.2.6 on 2021-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycle',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='productionstatus',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
