# Generated by Django 2.2.6 on 2020-10-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0013_auto_20201026_1336'),
        ('product', '0002_auto_20201026_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='engineering.Project'),
        ),
    ]
