# Generated by Django 2.2.6 on 2020-10-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_production_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='lifecycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='product.Lifecycle'),
        ),
        migrations.AlterField(
            model_name='production',
            name='sn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='产品编号'),
        ),
    ]
