# Generated by Django 2.2.6 on 2020-10-22 14:54

from django.db import migrations, models
import django.db.models.deletion
import utils.basemodel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='通道名称')),
                ('count', models.IntegerField(verbose_name='通道数量')),
            ],
            options={
                'verbose_name': '通道信息',
                'verbose_name_plural': '通道信息',
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='采集器名称')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='采集器照片')),
                ('memo', models.TextField(verbose_name='备注')),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='engineering.Aisle')),
            ],
            options={
                'verbose_name': '采集器',
                'verbose_name_plural': '采集器',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='风机名称')),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='风机运行状态')),
                ('memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目风机',
                'verbose_name_plural': '项目风机',
            },
        ),
        migrations.CreateModel(
            name='FacilityCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=64, verbose_name='采集器编号')),
                ('types', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='采集类型')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('net_mask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('gate_way', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('model', models.CharField(max_length=64, verbose_name='目前版本')),
                ('collector_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_collector', to='engineering.Collector')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='engineering.Facility')),
            ],
            options={
                'verbose_name': '风机采集器',
                'verbose_name_plural': '风机采集器',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='厂商名称')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='厂商电话')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='MonitorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='监测名称')),
            ],
            options={
                'verbose_name': '监测类型',
                'verbose_name_plural': '监测类型',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(verbose_name='项目类型')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('area', models.SmallIntegerField(blank=True, null=True, verbose_name='区域')),
                ('priority', models.SmallIntegerField(default=1, verbose_name='优先级')),
                ('working_env', models.SmallIntegerField(blank=True, null=True, verbose_name='作业环境')),
                ('address', models.CharField(max_length=64, verbose_name='项目地址')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='内部项目编号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='项目状态')),
                ('facility_count', models.IntegerField(default=0, verbose_name='设备数量')),
                ('contractor', models.CharField(max_length=64, verbose_name='承包商')),
                ('manager', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目负责人')),
                ('image', models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to=utils.basemodel.upload_path_image, verbose_name='默认图片')),
                ('entrance_time', models.DateTimeField(blank=True, null=True, verbose_name='入场时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('manufacturers', models.ManyToManyField(db_constraint=False, related_name='project', to='engineering.Manufacturer')),
                ('monitor_type', models.ManyToManyField(db_constraint=False, related_name='project', to='engineering.MonitorType')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('server_type', models.CharField(max_length=32, verbose_name='服务器类型')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌')),
                ('model', models.CharField(max_length=64, verbose_name='服务器型号')),
                ('os_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本')),
                ('place', models.CharField(blank=True, max_length=64, null=True, verbose_name='存放位置')),
                ('accounts', models.CharField(blank=True, max_length=32, null=True, verbose_name='帐号')),
                ('passwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='engineering.Project')),
            ],
            options={
                'verbose_name': '风场服务器',
                'verbose_name_plural': '风场服务器',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='传感器名称')),
                ('bias_voltage', models.CharField(blank=True, max_length=32, null=True, verbose_name='偏置电压')),
                ('memo', models.TextField(verbose_name='备注')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='engineering.Manufacturer')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('capacity', models.IntegerField(blank=True, default=8, null=True, verbose_name='内存大小')),
                ('ram_count', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='内存数量')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='engineering.Server')),
            ],
            options={
                'verbose_name': '内存',
                'verbose_name_plural': '内存',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='网卡名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('net_mask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('gate_way', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='engineering.Server')),
            ],
            options={
                'verbose_name': '网卡',
                'verbose_name_plural': '网卡',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='机器型号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='engineering.Manufacturer')),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号',
            },
        ),
        migrations.CreateModel(
            name='FacilitySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=64, verbose_name='采集器编号')),
                ('number', models.SmallIntegerField(default=1, verbose_name='通道编号')),
                ('install_site', models.CharField(blank=True, max_length=64, null=True, verbose_name='安装位置')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='engineering.FacilityCollector')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_sensor', to='engineering.Sensor')),
            ],
            options={
                'verbose_name': '风机传感器',
                'verbose_name_plural': '风机传感器',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.Machine'),
        ),
        migrations.AddField(
            model_name='facility',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='engineering.Project'),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('event_type', models.SmallIntegerField(default=1, verbose_name='事件类型')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
                ('detail', models.TextField(verbose_name='事件详情')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='engineering.Project')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('disk_type', models.CharField(max_length=16, verbose_name='硬件类型')),
                ('disk_capacity', models.FloatField(verbose_name='硬盘容量(GB)')),
                ('disk_count', models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='硬盘数量')),
                ('disk_raid', models.CharField(blank=True, max_length=16, null=True, verbose_name='阵列类型')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='engineering.Server')),
            ],
            options={
                'verbose_name': '硬盘',
                'verbose_name_plural': '硬盘',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('cpu_core_count', models.SmallIntegerField(blank=True, default=4, null=True, verbose_name='CPU核心数')),
                ('cpu_count', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='CPU物理个数')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='engineering.Server')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
    ]
