# Generated by Django 2.2.6 on 2020-09-02 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '风场服务器', 'verbose_name_plural': '风场服务器'},
        ),
        migrations.AddField(
            model_name='collector',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facilitycollector',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facilitysensor',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nic',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='project',
            name='builders',
            field=models.ManyToManyField(db_constraint=False, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.SmallIntegerField(default=1, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_core_count',
            field=models.SmallIntegerField(blank=True, default=4, null=True, verbose_name='CPU核心数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_count',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='CPU物理个数'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='disk_count',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='硬盘数量'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='disk_raid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='阵列类型'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='风机运行状态'),
        ),
        migrations.AlterField(
            model_name='facilitycollector',
            name='types',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='采集类型'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='厂商电话'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_count',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='内存数量'),
        ),
        migrations.AlterField(
            model_name='server',
            name='accounts',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='帐号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_release',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='passwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='server',
            name='place',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='存放位置'),
        ),
    ]
