# Generated by Django 2.2.6 on 2020-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20200724_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_core_count',
            field=models.SmallIntegerField(default=4, verbose_name='CPU核心数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_count',
            field=models.SmallIntegerField(default=1, verbose_name='CPU物理个数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='内部项目编号'),
        ),
    ]
