# Generated by Django 2.2.6 on 2020-11-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20201116_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outsourcer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='承包商类型')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='承包商名称')),
                ('scale', models.CharField(blank=True, max_length=32, null=True, verbose_name='承包商规模')),
                ('linkman', models.CharField(blank=True, max_length=32, null=True, verbose_name='承包商联系人')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='承包商联系人手机')),
                ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='加入时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '承包商',
                'verbose_name_plural': '承包商',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stock_finish',
            field=models.CharField(blank=True, default='未完成', max_length=16, null=True, verbose_name='发货状态'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('context', models.TextField(blank=True, null=True, verbose_name='承包内容')),
                ('payment', models.IntegerField(blank=True, null=True, verbose_name='承包货款')),
                ('payment_rate', models.CharField(blank=True, max_length=16, null=True, verbose_name='货款进度')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='加入时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='engineering.Outsourcer', verbose_name='承包商信息')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='engineering.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '承包信息',
                'verbose_name_plural': '承包信息',
            },
        ),
    ]
