# Generated by Django 2.2.6 on 2020-09-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20200902_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='监测名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_type', to='engineering.Project')),
            ],
            options={
                'verbose_name': '监测类型',
                'verbose_name_plural': '监测类型',
            },
        ),
    ]
