# Generated by Django 2.2.6 on 2021-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20210310_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目完成时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='entrance_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计入场时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间'),
        ),
    ]
