# Generated by Django 2.2.6 on 2020-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20201209_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='加入时间'),
        ),
    ]
