# Generated by Django 2.2.6 on 2020-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20201029_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pj_sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='内部编号'),
        ),
    ]
