# Generated by Django 2.2.6 on 2021-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20210804_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarea',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='projectpriority',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='projectworkingenv',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='stockfinish',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
