# Generated by Django 2.2.6 on 2021-03-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20210304_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目开始时间'),
        ),
    ]
