# Generated by Django 2.2.6 on 2020-09-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_monitortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default=1, max_length=16, verbose_name='项目类型'),
            preserve_default=False,
        ),
    ]
