# Generated by Django 2.2.6 on 2020-10-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20201030_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_car',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目负责人'),
        ),
    ]
