# Generated by Django 2.2.6 on 2021-03-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20210311_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_time',
        ),
        migrations.AddField(
            model_name='project',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验收时间'),
        ),
    ]
