# Generated by Django 2.2.6 on 2020-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20201023_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortype',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='monitortype',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='monitortype',
            name='update_time',
        ),
    ]
