# Generated by Django 2.2.6 on 2020-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20200727_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_count',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram_count',
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_count',
            field=models.SmallIntegerField(default=2, verbose_name='硬盘数量'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_count',
            field=models.SmallIntegerField(default=1, verbose_name='内存数量'),
        ),
    ]
