# Generated by Django 2.2.6 on 2021-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20210810_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortype',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='tracestatus',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
