# Generated by Django 2.2.6 on 2021-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_project_begin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序'),
        ),
    ]
