# Generated by Django 2.2.6 on 2020-07-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_auto_20200727_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='disk_type',
            field=models.CharField(max_length=16, verbose_name='硬件类型'),
        ),
    ]
