# Generated by Django 2.2.6 on 2020-09-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_type', to='engineering.Project'),
        ),
    ]
