# Generated by Django 2.2.6 on 2021-08-19 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0004_auto_20210811_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FAEman',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='FAEman_project', to=settings.AUTH_USER_MODEL, verbose_name='技术支持人员'),
        ),
        migrations.AddField(
            model_name='project',
            name='out_warranty',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出质保时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='submitter',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='关联-(user) 提交人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collect',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='collect', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='project',
            name='diagnosisman',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='diagnosis_project', to=settings.AUTH_USER_MODEL, verbose_name='诊断人员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='salesman',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='sales_project', to=settings.AUTH_USER_MODEL, verbose_name='销售人员'),
        ),
    ]
