# Generated by Django 2.2.6 on 2020-10-31 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0004_auto_20201030_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='内容')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='engineering.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目跟踪情况',
                'verbose_name_plural': '项目跟踪情况',
            },
        ),
    ]
