# Generated by Django 2.2.6 on 2020-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_auto_20201126_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_rate',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='货款进度'),
        ),
    ]
