# Generated by Django 2.2.6 on 2020-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_auto_20200910_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortype',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='monitor_type',
            field=models.ManyToManyField(db_constraint=False, related_name='project', to='engineering.MonitorType'),
        ),
    ]
