# Generated by Django 2.2.6 on 2020-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_auto_20201023_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='承包商'),
        ),
    ]
