# Generated by Django 2.2.6 on 2020-07-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_auto_20200728_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_raid',
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_raid',
            field=models.CharField(default=1, max_length=16, verbose_name='阵列类型'),
            preserve_default=False,
        ),
    ]
