# Generated by Django 2.2.6 on 2021-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_auto_20210819_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrority2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='优先级名称')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '优先级2',
                'verbose_name_plural': '优先级2',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='priority2',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='project2', to='engineering.ProjectPrority2'),
        ),
    ]
