# Generated by Django 2.2.6 on 2020-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_auto_20200728_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='nic',
            name='memo',
            field=models.TextField(default=1, verbose_name='备注'),
            preserve_default=False,
        ),
    ]
