# Generated by Django 2.2.6 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_auto_20200911_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='builders',
        ),
        migrations.AddField(
            model_name='project',
            name='facility_count',
            field=models.IntegerField(default=0, verbose_name='设备数量'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='disk',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='facilitycollector',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='facilitysensor',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='monitortype',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='nic',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ram',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
