# Generated by Django 2.2.6 on 2020-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_auto_20201023_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='working_env',
        ),
        migrations.RemoveField(
            model_name='monitortype',
            name='project',
        ),
        migrations.AddField(
            model_name='monitortype',
            name='project',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='monitor_type', to='engineering.Project'),
        ),
        migrations.CreateModel(
            name='Workingenv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='环境名称')),
                ('project', models.ManyToManyField(blank=True, db_constraint=False, related_name='working_env', to='engineering.Project')),
            ],
            options={
                'verbose_name': '作业环境',
                'verbose_name_plural': '作业环境',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='状态名称')),
                ('project', models.ManyToManyField(blank=True, db_constraint=False, related_name='status', to='engineering.Project')),
            ],
            options={
                'verbose_name': '项目状态',
                'verbose_name_plural': '项目状态',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='区域名称')),
                ('project', models.ManyToManyField(blank=True, db_constraint=False, related_name='area', to='engineering.Project')),
            ],
            options={
                'verbose_name': '区域信息',
                'verbose_name_plural': '区域信息',
            },
        ),
    ]
