# Generated by Django 2.2.6 on 2020-07-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_nic_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='brand',
            field=models.CharField(max_length=32, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(max_length=32, verbose_name='服务器类型'),
        ),
    ]
