# Generated by Django 2.2.6 on 2020-10-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_auto_20201023_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='engineering.ProjectType', verbose_name='项目类型'),
        ),
    ]
