# Generated by Django 2.2.6 on 2020-10-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_auto_20200915_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='通道名称')),
                ('count', models.IntegerField(verbose_name='通道数量')),
            ],
            options={
                'verbose_name': '通道信息',
                'verbose_name_plural': '通道信息',
            },
        ),
        migrations.AlterField(
            model_name='collector',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='engineering.Aisle'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='model',
            field=models.CharField(max_length=64, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='区域'),
        ),
    ]
