# Generated by Django 2.2.6 on 2020-10-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_auto_20201023_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '区域信息',
                'verbose_name_plural': '区域信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkingEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='环境名称')),
            ],
            options={
                'verbose_name': '作业环境',
                'verbose_name_plural': '作业环境',
            },
        ),
        migrations.RemoveField(
            model_name='workingenv',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectstatus',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='engineering.ProjectStatus', verbose_name='项目状态'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Workingenv',
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='engineering.ProjectArea', verbose_name='项目区域'),
        ),
        migrations.AddField(
            model_name='project',
            name='working_env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='engineering.ProjectWorkingEnv', verbose_name='项目作业环境'),
        ),
    ]
