# Generated by Django 2.2.6 on 2020-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_auto_20201020_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(default=1, max_length=64, verbose_name='承包商'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='working_env',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='作业环境'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='区域'),
        ),
    ]
