# Generated by Django 2.2.6 on 2020-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_auto_20200728_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='accounts',
            field=models.CharField(default=1, max_length=32, verbose_name='帐号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='passwd',
            field=models.CharField(default=1, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='place',
            field=models.CharField(default=1, max_length=64, verbose_name='存放位置'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='os_release',
            field=models.CharField(max_length=64, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(max_length=32, verbose_name='系统类型'),
        ),
    ]
