# Generated by Django 2.2.6 on 2020-10-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0009_auto_20201023_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='采集器名称')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
                ('hardversion', models.CharField(max_length=64, verbose_name='硬件版本')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='采集器照片')),
                ('memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '采集器',
                'verbose_name_plural': '采集器',
            },
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='server',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='server',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='project',
        ),
        migrations.RemoveField(
            model_name='facilitycollector',
            name='collector_type',
        ),
        migrations.RemoveField(
            model_name='facilitycollector',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilitysensor',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='facilitysensor',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='server',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='server',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='server',
            name='project',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='date',
        ),
        migrations.AddField(
            model_name='machine',
            name='param',
            field=models.TextField(blank=True, null=True, verbose_name='设备参数'),
        ),
        migrations.AlterField(
            model_name='aisle',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='通道数量'),
        ),
        migrations.DeleteModel(
            name='Collector',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityCollector',
        ),
        migrations.DeleteModel(
            name='FacilitySensor',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AddField(
            model_name='product',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='engineering.Aisle'),
        ),
    ]
