# Generated by Django 2.2.6 on 2020-07-29 07:43

from django.db import migrations, models
import django.db.models.deletion
import utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0009_auto_20200728_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': '日志', 'verbose_name_plural': '日志'},
        ),
        migrations.AddField(
            model_name='facilitycollector',
            name='collector_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facility_collector', to='engineering.Collector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitysensor',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='engineering.FacilityCollector'),
        ),
        migrations.AlterField(
            model_name='facilitysensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_sensor', to='engineering.Sensor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to=utils.basemodel.upload_path_image, verbose_name='默认图片'),
        ),
    ]
