# Generated by Django 2.2.6 on 2020-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0009_auto_20201020_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.SmallIntegerField(verbose_name='项目类型'),
        ),
    ]
