# Generated by Django 2.2.6 on 2020-07-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_auto_20200729_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64, verbose_name='厂商名称')),
                ('telephone', models.CharField(max_length=11, verbose_name='厂商电话')),
                ('memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': '设备型号', 'verbose_name_plural': '设备型号'},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='engineering.Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='engineering.Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='manufacturers',
            field=models.ManyToManyField(db_constraint=False, related_name='project', to='engineering.Manufacturer'),
        ),
    ]
