# Generated by Django 2.2.6 on 2020-10-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_auto_20201024_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aisle',
        ),
        migrations.DeleteModel(
            name='Aisle',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
