# Generated by Django 2.2.6 on 2020-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_auto_20201020_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(default=1, max_length=64, verbose_name='项目负责人'),
            preserve_default=False,
        ),
    ]
