# Generated by Django 2.2.6 on 2020-10-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0011_auto_20201024_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdcRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=64, verbose_name='SN号或快速服务代码')),
                ('describe', models.TextField(verbose_name='设备描述')),
                ('software', models.CharField(max_length=32, verbose_name='安装软件版本')),
                ('ip', models.TextField(verbose_name='ip信息')),
                ('memo', models.TextField(verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcroom', to='engineering.Project')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
            },
        ),
    ]
