# Generated by Django 2.2.6 on 2020-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0012_idcroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcroom',
            name='ip',
            field=models.TextField(blank=True, null=True, verbose_name='ip信息'),
        ),
        migrations.AlterField(
            model_name='idcroom',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='idcroom',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SN号或快速服务代码'),
        ),
        migrations.AlterField(
            model_name='idcroom',
            name='software',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='安装软件版本'),
        ),
    ]
