# Generated by Django 2.2.6 on 2020-10-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.basemodel


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0013_auto_20201026_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='文件名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.basemodel.upload_path_image, verbose_name='图片')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '库存管理', 'verbose_name_plural': '库存管理'},
        ),
        migrations.AddField(
            model_name='stock',
            name='delivered',
            field=models.IntegerField(default=1, verbose_name='已发货'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='货物名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='totality',
            field=models.IntegerField(default=1, verbose_name='货物总数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engineering.MonitorType', verbose_name='货物类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='undelivered',
            field=models.IntegerField(default=1, verbose_name='未发货'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, verbose_name='货物名称')),
                ('type', models.CharField(max_length=32, verbose_name='发货类型')),
                ('count', models.IntegerField(verbose_name='发货数量')),
                ('memo', models.TextField(verbose_name='备注')),
                ('img', models.ManyToManyField(db_constraint=False, related_name='project', to='engineering.InvoiceImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发货人')),
            ],
            options={
                'verbose_name': '发货清单',
                'verbose_name_plural': '发货清单',
            },
        ),
    ]
