# Generated by Django 2.2.6 on 2020-10-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0014_auto_20201026_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='发货数量'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发货类型'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivered',
            field=models.IntegerField(blank=True, null=True, verbose_name='已发货'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totality',
            field=models.IntegerField(blank=True, null=True, verbose_name='货物总数'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.MonitorType', verbose_name='货物类型'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='undelivered',
            field=models.IntegerField(blank=True, null=True, verbose_name='未发货'),
        ),
    ]
