# Generated by Django 2.2.6 on 2020-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0015_auto_20201026_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceimage',
            options={'verbose_name': '发货图片', 'verbose_name_plural': '发货图片'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='img',
            field=models.ManyToManyField(db_constraint=False, related_name='invoice', to='engineering.InvoiceImage'),
        ),
    ]
