# Generated by Django 2.2.6 on 2020-10-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0016_auto_20201026_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='img',
        ),
    ]
