# Generated by Django 2.2.6 on 2020-10-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0017_remove_invoice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceimage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='engineering.InvoiceImage'),
        ),
    ]
