# Generated by Django 2.2.6 on 2020-10-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0019_auto_20201026_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标签')),
            ],
            options={
                'verbose_name': '库存完成与否',
                'verbose_name_plural': '库存完成与否',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已发货'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='undelivered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='未发货'),
        ),
        migrations.AddField(
            model_name='stock',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.StockFinish', verbose_name='是否完成'),
        ),
    ]
