# Generated by Django 2.2.6 on 2020-10-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0020_auto_20201026_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceimage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='engineering.Invoice'),
        ),
    ]
