# Generated by Django 2.2.6 on 2020-11-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='market',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='market',
            name='r3',
        ),
        migrations.RemoveField(
            model_name='market',
            name='r4',
        ),
        migrations.AddField(
            model_name='raterecord',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='crm.Market', verbose_name='命中率记录'),
        ),
    ]
