# Generated by Django 2.2.6 on 2020-12-20 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20201209_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='预额')),
                ('rate_0', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='0')),
                ('rate_025', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='0.25')),
                ('rate_050', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='0.5')),
                ('rate_075', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='0.75')),
                ('rate_100', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='1')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('user', models.ManyToManyField(db_constraint=False, related_name='markethistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
