# Generated by Django 2.2.6 on 2020-11-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201126_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='raterecord',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='crm.Market', verbose_name='命中率记录'),
        ),
    ]
