# Generated by Django 2.2.6 on 2020-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_markethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethistory',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='预额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_0',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='0'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_025',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='0.25'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_050',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='0.5'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_075',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='0.75'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='1'),
        ),
    ]
