# Generated by Django 2.2.6 on 2020-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201127_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raterecord',
            name='days',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='天数'),
        ),
    ]
