# Generated by Django 2.2.6 on 2020-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201220_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='markethistory',
            name='estimated_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='预额'),
        ),
        migrations.AddField(
            model_name='markethistory',
            name='rate_025_t',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='25%个数'),
        ),
        migrations.AddField(
            model_name='markethistory',
            name='rate_050_t',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='50%个数'),
        ),
        migrations.AddField(
            model_name='markethistory',
            name='rate_075_t',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='75%个数'),
        ),
        migrations.AddField(
            model_name='markethistory',
            name='rate_0_t',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='0%个数'),
        ),
        migrations.AddField(
            model_name='markethistory',
            name='rate_100_t',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='100%个数'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='漏额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_0',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='0%预额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_025',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='25%预额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_050',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='50%预额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_075',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='75%预额'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='rate_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='100%预额'),
        ),
    ]
