# Generated by Django 2.2.6 on 2020-12-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201220_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markethistory',
            options={'verbose_name': '月历史记录', 'verbose_name_plural': '月历史记录'},
        ),
    ]
