# Generated by Django 2.2.6 on 2020-12-22 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20201221_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='user',
        ),
        migrations.AddField(
            model_name='market',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to=settings.AUTH_USER_MODEL),
        ),
    ]
