# Generated by Django 2.2.6 on 2020-12-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_auto_20201222_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markethistory',
            name='user',
        ),
        migrations.AddField(
            model_name='markethistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markethistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
