# Generated by Django 2.2.6 on 2020-12-04 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='user',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
