# Generated by Django 2.2.6 on 2020-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='role',
        ),
        migrations.AddField(
            model_name='menu',
            name='role',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='menu', to='rbac.Auth'),
        ),
    ]
