# Generated by Django 2.2.6 on 2020-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
