# Generated by Django 2.2.6 on 2020-11-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='menu',
        ),
        migrations.AddField(
            model_name='auth',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='rbac.Menu'),
        ),
        migrations.RemoveField(
            model_name='auth',
            name='user',
        ),
        migrations.AddField(
            model_name='auth',
            name='user',
            field=models.ManyToManyField(db_constraint=False, related_name='auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
