# Generated by Django 2.2.6 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200902_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
