# Generated by Django 2.2.6 on 2020-11-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20201105_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='role',
            new_name='title',
        ),
    ]
