# Generated by Django 2.2.6 on 2020-10-16 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0003_auto_20200915_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='leader',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='memo',
            field=models.TextField(default=1, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=1, verbose_name='是否开启'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Menu'),
        ),
    ]
