# Generated by Django 2.2.6 on 2020-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20201016_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='leader',
        ),
        migrations.AddField(
            model_name='role',
            name='leader',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
