# Generated by Django 2.2.6 on 2020-11-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20201105_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='title',
            field=models.CharField(max_length=32, verbose_name='管理员角色'),
        ),
    ]
