# Generated by Django 2.2.6 on 2020-10-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20201017_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='leader',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名称'),
        ),
    ]
