# Generated by Django 2.2.6 on 2020-11-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20201105_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='前端名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.Menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='路径'),
        ),
    ]
