# Generated by Django 2.2.6 on 2020-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20201017_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(db_constraint=False, related_name='role', to='rbac.Menu'),
        ),
    ]
